### PR TITLE
docs: initial import of Zephyr requirements to SDoc files

### PR DESCRIPTION
**Pull request by stanislaw**
This changeset has been generated by importing requirements from an Excel file containing Zephyr requirements, which was authored by the Zephyr Safety Working Group. The new requirements are stored in the SDoc markup and can be viewed using [StrictDoc](https://github.com/strictdoc-project/strictdoc) tool. The instructions have been added to the README file accordingly.

This changeset also contains the removal of Doorstop files that were added to this repository in April 2021. This has been agreed by the Zephyr Safety Working Group, and I am doing this removal on behalf of the group.

I have added a few most obvious TBDs. My changes are only minimal and do not modify any existing content. All changes should be reviewable commit by commit in the branch.

### CODE REVIEW

**Comment by simhein** [comment]
@stanislaw Nice work so far and it is working really good. I think we should add a status before we go further with this PR. What do you think?

**Comment by stanislaw** [comment]
> @stanislaw Nice work so far and it is working really good. I think we should add a status before we go further with this PR. What do you think?

Sure! Would you like every requirement to have a `STATUS: Draft` field?

**Comment by simhein** [comment]
> > @stanislaw Nice work so far and it is working really good. I think we should add a status before we go further with this PR. What do you think?
> 
> Sure! Would you like every requirement to have a `STATUS: Draft` field?

Yes I think that would fit the best in the actual state.

**Comment by stanislaw** [comment]
> > Sure! Would you like every requirement to have a `STATUS: Draft` field?
> 
> Yes I think that would fit the best in the actual state.

The STATUS field has been added just now.

**Comment by stanislaw** [comment]
The next (quick) MR could address the removal of Doorstop files as well as the introduction of a StrictDoc export command to run on CI.

I prefer to do the CI one as a separate one because I may need to debug it a little, and this could clutter the commit history/discussion on this PR.

**Comment by simhein** [comment]
> The next (quick) MR could address the removal of Doorstop files as well as the introduction of a StrictDoc export command to run on CI.
> 
> I prefer to do the CI one as a separate one because I may need to debug it a little, and this could clutter the commit history/discussion on this PR.

I think that is a good approach. Should I do the removal of the Doorstop files, because I think this was on my plate :)

**Comment by stanislaw** [comment]
> > The next (quick) MR could address the removal of Doorstop files as well as the introduction of a StrictDoc export command to run on CI.
> > I prefer to do the CI one as a separate one because I may need to debug it a little, and this could clutter the commit history/discussion on this PR.
> 
> I think that is a good approach. Should I do the removal of the Doorstop files, because I think this was on my plate :)

I could remove at the same time while doing the CI changes because the CI script and the requirements.txt files are to be edited anyway. I am fine to proceed either way.

**Comment by simhein** [comment]
> > > The next (quick) MR could address the removal of Doorstop files as well as the introduction of a StrictDoc export command to run on CI.
> > > I prefer to do the CI one as a separate one because I may need to debug it a little, and this could clutter the commit history/discussion on this PR.
> > 
> > 
> > I think that is a good approach. Should I do the removal of the Doorstop files, because I think this was on my plate :)
> 
> I could remove at the same time while doing the CI changes because the CI script and the requirements.txt files are to be edited anyway. I am fine to proceed either way.

Okay In this case it would make sens if you remove the staff so the context is clear why this was removed and what was done

**Comment by stanislaw** [comment]
> > > > The next (quick) MR could address the removal of Doorstop files as well as the introduction of a StrictDoc export command to run on CI.
> > > > I prefer to do the CI one as a separate one because I may need to debug it a little, and this could clutter the commit history/discussion on this PR.
> > > 
> > > 
> > > I think that is a good approach. Should I do the removal of the Doorstop files, because I think this was on my plate :)
> > 
> > 
> > I could remove at the same time while doing the CI changes because the CI script and the requirements.txt files are to be edited anyway. I am fine to proceed either way.
> 
> Okay In this case it would make sens if you remove the staff so the context is clear why this was removed and what was done

Yes, I will provide a description on the CI PR.

**Comment by stanislaw** [comment]
@simhein I realized, I could simply push the CI commit on top of this PR. Please review the commit and the updated PR text. Let me know if you would like me to add further details in the description.

The CI workflow is not triggered because it is "awaiting approval", and so I cannot tell if the CI is happy. Once you approve the CI to run, we will see if the new CI sequence works without issues.

**Comment by simhein** [comment]
> @simhein I realized, I could simply push the CI commit on top of this PR. Please review the commit and the updated PR text. Let me know if you would like me to add further details in the description.
> 
> The CI workflow is not triggered because it is "awaiting approval", and so I cannot tell if the CI is happy. Once you approve the CI to run, we will see if the new CI sequence works without issues.

Triggered the run and it looks good to me.

One thing I totally missed and should be added to the commits is the sign off of the commits because we have the 
Developer Certification of Origin contribution guidelines (https://docs.zephyrproject.org/latest/contribute/guidelines.html#developer-certification-of-origin-dco) which applies to all the repositories of the project.

**Comment by stanislaw** [comment]
> Triggered the run and it looks good to me.
> 
> One thing I totally missed and should be added to the commits is the sign off of the commits because we have the Developer Certification of Origin contribution guidelines (https://docs.zephyrproject.org/latest/contribute/guidelines.html#developer-certification-of-origin-dco) which applies to all the repositories of the project.

I have just added the sign-off lines to each commit.

**Review by simhein — APPROVED** [review]

**Pull request merged**
